console.log("===========BankName=================");
var bankName;
console.log("Datatype of bankName:",bankName);
bankName="SBI Bank";
console.log("Bank name Is:",bankName);
var bankNameTypeOf = typeof bankName;
console.log("Data type of BankName Is:",bankNameTypeOf);
console.log("===========marks=================");
var marks="90%";
  marksTypeOf=typeof marks;
console.log("Data typeof marks is",marksTypeOf);
console.log("===========isworking=================");
var isworking;
console.log(isworking);
isworking=true;
console.log("Isworking",isworking);
isworkingTypeOf=typeof isworking;
console.log("Data type of isworking :",isworkingTypeOf);
console.log("===========TotalCount=================");
var totalcount="Hundred and Seven";
totalcountTypeOf=typeof totalcount;
console.log("Data type of totalcount:",totalcountTypeOf);
var totalcount=107;
totalcountTypeOf=typeof totalcount;
console.log("Data type of totalcount:",totalcountTypeOf);
